---
# tasks file for nginx
- name: nginx | add nginx repo
  template:
    src: repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
- name: Install nginx
  yum: name=nginx state=present
# - name: nginx | service nginx started and enabled
#   service: name=nginx state=started enabled=yes
- name: Nginx config
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
#   notify: restart nginx
